#!/usr/bin/env bash

function home_bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  pkg ensure chat/irssi

  rsync -ia $PKGWIPDIR/znc $PKGSRCDIR/net/
  pkg ensure net/znc
}

home_bootstrap "$@"
