#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if type -P irssi >/dev/null; then
    return 0
  fi

  return 1
}

source sub "$BASH_SOURCE" "$@"
